services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" 
    networks:
      - iot-net
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
  api:
    build:
      context: ./backend/api
    ports:
      - "8000:8000"
    networks:
      - iot-net
    env_file:
      - ./.env
    depends_on:
      - db
  simulator:
    build:
      context: ./sensor-simulation/simulator
    depends_on:
      - api
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge
volumes:
  db-data:
